### ISSUE TITLE
Could not translate host name

### ISSUE THREAD

**Issue by austinh** [ankane/pgslice#18]
Hello, I am getting this error when trying to connect to a postgres instance that is in a docker container. I have exposed this postgres instance on port 5092. I am able to connect to it in any other manner (psql, nodejs app outside of container, inside container, etc). Only pgslice doesn't seem to be working.

`pgslice prep reservations created_at month --url=postgres://postgres@localhost:5092/my_app_db`

I get this error:
```
could not translate host name "postgres://postgres@localhost:5092/my_app_db?" to address: nodename nor servname provided, or not known
```

Any ideas as to why this is happening?

**Comment by ankane** [comment]
Hey @austinh, what version of PgSlice are you on?

**Comment by austinh** [comment]
0.4.2 (latest I believe)

**Comment by ankane** [comment]
Please run `pgslice --version` to confirm

**Comment by ankane** [comment]
Nevermind, think I misread your last message. I'm not sure how to reproduce unfortunately. It's odd that there's a `?` at the end of the connection string.

**Comment by austinh** [comment]
If you have docker-compose, you can imitate this with the following configuration:

1. setup this docker-compose.yml
```yaml
# docker-compose.yml
 postgres:
    image: postgres:9.4.17-alpine
    ports:
      - "5094:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_app_db
```

2. psql into the container
```bash
docker-compose exec postgres psql -U postgres
```

3. create the database and table to test
```sql
CREATE DATABASE my_app_db;
```

`pgslice prep reservations created_at month --url=postgres://postgres@localhost:5094/my_app_db`
